---
BREW_TAP_PACKAGES:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
  - ktr0731/evans
  - osx-cross/avr
  - PX4/homebrew-px4

BREW_PACKAGES:
  - bash-completion
  - curl
  - cmake
  - evans
  - git
  - gnu-getopt
  - graphviz
  - hadolint
  - imagemagick
  - jq
  - libmagic
  - llvm
  - memcached
  - mysql
  - neovim
  - openssl
  - pandoc
  - protobuf
  - python
  - readline
  - reattach-to-user-namespace
  - shellcheck
  - tfenv
  - tig
  - tmux
  - translate-shell
  - vim
  - wget
  - yq
  # AVR
  - avr-gcc
  - dfu-programmer
  - gcc-arm-none-eabi
  - avrdude

BREW_CASK_PACKAGES:
  - boostnote
  - deepl
  - discord
  - docker-edge
  - firefox
  - gitify
  - grammarly
  - google-japanese-ime
  - google-chrome
  - kindle
  - kitematic
  - licecap
  - postman
  - raycast
  - rstudio
  - sequel-pro
  - slack
  - spectacle
  - spotify
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - xquartz
  - wireshark
