---
APT_PACKAGES:
  - apt-transport-https
  - autoconf
  - bash-completion
  - bison
  - bpfcc-tools
  - build-essential
  - ca-certificates
  - clang
  - cmake
  - curl
  - gcc
  - g++
  - make
  - xz-utils
  - zlib1g-dev
  # - libgdbm5
  - git
  - gnupg
  # - hadolint
  - imagemagick
  - jq
  - libc6-dev
  - libncurses5-dev
  - libffi-dev
  - libgmp-dev
  - libfontconfig1-dev
  - libfreetype6-dev
  - libxcb-xfixes0-dev
  - libmagic-dev
  - libmysqlclient-dev
  - libreadline6-dev
  - libssl-dev
  - libyaml-dev
  - llvm
  - lldb
  - multitime
  - mysql-client-core-8.0
  - neovim
  - pkg-config
  - pandoc
  - protobuf-compiler
  - python3-dev
  - python3-pip
  - shellcheck
  - software-properties-common
  - tmux
  - translate-shell
  - vim
  - xclip
  - zlib1g-dev

BREW_TAP_PACKAGES:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/core
  - homebrew/services
  - ktr0731/evans
  - osx-cross/avr
  - PX4/homebrew-px4

BREW_PACKAGES:
  - bash-completion
  - curl
  - cmake
  - evans
  - git
  - gnu-getopt
  - graphviz
  - hadolint
  - imagemagick
  - jq
  - libmagic
  - llvm
  - memcached
  - mysql
  - neovim
  - openssl
  - pandoc
  - protobuf
  - python
  - readline
  - reattach-to-user-namespace
  - shellcheck
  - tfenv
  - tig
  - tmux
  - translate-shell
  - vim
  - wget
  - yq
  # AVR
  - avr-gcc
  - dfu-programmer
  - gcc-arm-none-eabi
  - avrdude

BREW_CASK_PACKAGES:
  - boostnote
  - deepl
  - discord
  - docker-edge
  - firefox
  - gitify
  - grammarly
  - google-japanese-ime
  - google-chrome
  - kindle
  - kitematic
  - licecap
  - postman
  - raycast
  - rstudio
  - sequel-pro
  - slack
  - spectacle
  - spotify
  - vagrant
  - virtualbox
  - visual-studio-code
  - vlc
  - xquartz
  - wireshark
