- name: Install Alacritty
  shell: |
    brew tap mscharley/homebrew
    brew install --HEAD alacritty
  when: "ansible_os_family == 'Darwin'"

- name: Install Alacritty Dependencies
  apt:
    name: '{{ APT_PACKAGES }}'
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Fetch Alacritty repo
  git:
    repo: https://github.com/jwilm/alacritty
    dest: "$HOME/alacritty"
  when: "ansible_os_family == 'Debian'"

- name: Install Alacritty
  shell: |
    cargo install cargo-deb
    cargo deb --install
  args:
    chdir: "$HOME/alacritty/"
  when: "ansible_os_family == 'Debian'"
