- name: Brew Tap -> bundle core dupes services versions
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - homebrew/bundle
    - homebrew/cask
    - homebrew/cask-versions
    - homebrew/core
    - homebrew/services
    - ktr0731/evans
    - osx-cross/avr
    - PX4/homebrew-px4

- name: Brew Untap
  homebrew_tap:
    name: '{{ item }}'
    state: absent
  with_items:
    - homebrew/boneyard

- name: Brew Update
  shell: brew update

- name: Brew Install
  homebrew:
    name: '{{ BREW_PACKAGES | join(",") }}'
    state: present
  ignore_errors: yes

- name: Install Homebrew cask packages
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
    - boostnote
    - discord
    - docker-edge
    - firefox
    - gitify
    - google-japanese-ime
    - google-chrome
    - kindle
    - kitematic
    - licecap
    - postman
    - rstudio
    - sequel-pro
    - slack
    - spectacle
    - spotify
    - vagrant
    - virtualbox
    - visual-studio-code
    - vlc
    - xquartz
    - wireshark
  ignore_errors: yes
