- name: Ensure pyenv installed
  shell: bash -l -c 'which pyenv'
  changed_when: false

- name: Check installed python version
  shell: bash -l -c 'pyenv versions'
  register: PYENV_INSTALLED
  changed_when: false
  ignore_errors: yes

- name: Install python from pyenv
  shell: bash -l -c 'pyenv install {{ item }}'
  when: 'item not in PYENV_INSTALLED.stdout'
  with_items: '{{ PYTHON_VERSIONS }}'

- name: Place python ver manage script
  template:
    src: files/manage_python_ver.sh
    dest: ~/.bash.d/manage_python_ver.sh

- name: Grant execute attr
  shell: chmod +x ~/.bash.d/manage_python_ver.sh
