name: Ensure pyenv installed
  shell: bash -l -c 'which pyenv'
  changed_when: false

- name: Check installed python version
  shell: bash -l -c 'pyenv versions'
  register: PYENV_INSTALLED
  changed_when: false

- name: Install python from pyenv
  shell: pyenv install {{ item }}
  when: 'item not in PYENV_INSTALLED.stdout'
  with_items: '{{ PYTHON_VERSIONS }}'

- name: Set pyenv global individually
  shell: pyenv global {{ PY3_VERSION }} {{ PY2_VERSION }}

- name: Write python path
  lineinfile:
    dest: ~/.bash.d/manage_python_ver.sh
    line: '{{ item  }}'
    create: yes
  with_items:
    - export PATH="$HOME/.pyenv/versions/$PY3_VERSION/bin/:$PATH"
    - export PATH="$HOME/.pyenv/versions/$PY2_VERSION/bin/:$PATH"

- name: Grant execute attr
  shell: chmod +x ~/.bash.d/manage_python_ver.sh
