---
- name: Install snap
  become: true
  community.general.snap:
    name:
      - discrod
      - slack
      - sportify
      - wireshark
      - zoom-client
    state: present
  tags:
    - config-base
    - config-packages
