---
- name: Install snap
  become: true
  community.general.snap:
    name:
      - discord
      - slack
      - spotify
      - zoom-client
    state: present
  tags:
    - config-base
    - config-packages
