- name: Install anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: "$HOME/.anyenv"

- name: Install anyenv-update
  git:
    repo: https://github.com/znz/anyenv-update
    dest: "$HOME/.anyenv/plugins/anyenv-update"

- name: Write anyenv init
  lineinfile:
    dest: "$HOME/.bash.d/anyenv.sh"
    line: '{{ item }}'
    create: yes
    mode: 755
  with_items:
    - export PATH="$HOME/.anyenv/bin:$PATH"
    - eval "$(anyenv init -)"

- name: Check env installed
  shell: bash -l -c 'anyenv envs'
  register: anyenv_envs
  changed_when: false

- name: Install env tools
  shell: bash -l -c 'anyenv install {{ item }}'
  with_items: '{{ ANYENV_ENVS }}'
  when: 'item not in anyenv_envs.stdout'

- name: Update exists tools
  shell: bash -l -c 'anyenv update'
