- name: Install anyenv
  git:
    repo: https://github.com/riywo/anyenv
    dest: "$HOME/.anyenv"

- name: Install anyenv-update
  git:
    repo: https://github.com/znz/anyenv-update
    dest: "$HOME/.anyenv/plugins/anyenv-update"

- name: Place anyenv.sh
  template:
    src: files/anyenv.sh
    dest: "$HOME/.bash.d/anyenv.sh"
    mode: 0755

- name: Place goenv.sh
  template:
    src: files/goenv.sh
    dest: "$HOME/.bash.d/goenv.sh"
    mode: 0755

- name: Enable anyenv
  shell: exec $SHELL -l

- name: Check env installed
  shell: anyenv envs
  register: anyenv_envs
  changed_when: false

- name: Install env tools
  shell: anyenv install '{{ item }}'
  with_items: '{{ ANYENV_ENVS }}'
  when: 'item not in anyenv_envs.stdout'

- name: Update exists tools
  shell: anyenv update

- name: Enable anyenv
  shell: exec $SHELL -l
