- name: Install ctags/gtags
  shell: |
    brew tap universal-ctags/universal-ctags
    brew install --HEAD universal-ctags/universal-ctags/universal-ctags
    brew install global --with-pygments

- name: Install ricty font
  shell: |
    brew tap sanemat/font
    brew install ricty
    cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/
    fc-cache -vf

- name: Install vim-plug
  shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install nvim client
  shell: pip3 install neovim

- name: Install Alacritty
  shell: |
    brew tap mscharley/homebrew
    brew install --HEAD alacritty

- name: Install onelogin-aws-cli
  shell: pip3 install onelogin-aws-cli

- name: Enable dotfiles
  shell: . ~/.bash_profile
