- name: Install ctags/gtags
  shell: |
    brew tap universal-ctags/universal-ctags
    brew install --HEAD universal-ctags/universal-ctags/universal-ctags
    brew install global --with-pygments
  when: "ansible_os_family == 'Darwin'"

- name: Add Apt-Repository
  become: yes
  apt_repository:
    repo: ppa:hnakamur/universal-ctags
  when: ("ansible_os_family == 'Debian'")
  ignore_errors: yes

- name: Install ctags/gtags
  become: yes
  apt:
    name: universal-ctags
    state: present
  when: ("ansible_os_family == 'Debian'")
  ignore_errors: yes

- name: Install vim-plug
  shell: |
    curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install nvim client
  shell: pip3 install neovim
  args:
    executable: /bin/bash

- name: Place fzf.sh
  template:
    src: files/fzf.sh
    dest: "$HOME/.bash.d/fzf.sh"
    mode: 0755

- name: Install onelogin-aws-cli
  shell: pip3 install onelogin-aws-cli
  args:
    executable: /bin/bash

- name: Install eksctl
  shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin
  args:
    executable: /bin/bash

- name: Install aws-iam-authenticator
  shell: go get -u github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator
  args:
    executable: /bin/bash

- name: Enable dotfiles
  shell: $SHELL -l
