- name: Install ctags/gtags
  shell: |
    brew tap universal-ctags/universal-ctags
    brew install --HEAD universal-ctags/universal-ctags/universal-ctags
    brew install global --with-pygments
  when: "ansible_os_family == 'Darwin'"

- name: Add Apt-Repository
  apt_repository:
    repo: ppa:hnakamur/universal-ctags
  when: "ansible_os_family == 'Debian'"

- name: Install ctags/gtags
  become: yes
  apt:
    name: universal-ctags
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Install vim-plug
  shell: |
    curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install nvim client
  shell: pip3 install neovim
  args:
    executable: /bin/bash

- name: Place fzf.sh
  template:
    src: files/fzf.sh
    dest: "$HOME/.bash.d/fzf.sh"
    mode: 0755

- name: Install onelogin-aws-cli
  shell: pip3 install onelogin-aws-cli
  args:
    executable: /bin/bash

- name: Install ripgrep
  shell: brew install ripgrep
  when: "ansible_os_family == 'Darwin'"

- name: Install ripgrep
  become: yes
  shell: |
    curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb
    dpkg -i ripgrep_0.10.0_amd64.deb
  when: "ansible_os_family == 'Debian'"

- name: Install fd
  shell: brew install fd
  when: "ansible_os_family == 'Darwin'"

- name: Install fd
  become: yes
  apt:
    name: fd-find
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Enable dotfiles
  shell: exec $SHELL -l
