- name: Brew Tap -> bundle core dupes services versions
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - homebrew/bundle
    - homebrew/core
    - homebrew/services
    - homebrew/cask

- name: Brew Update
  shell: brew update

- name: Copy Brewfile
  template:
    src: files/Brewfile
    dest: ~/.Brewfile

- name: Brew bundle w/ Brewfile
  shell: brew bundle --global
  ignore_errors: yes
