- name: Install Dependencies
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ UBUNTU_DEPENDENCIES }}'
  when: "ansible_os_family == 'Debian'"

- name: Install Stack
  shell: |
    if ! which stack > /dev/null 2>&1; then
      curl -sSL https://get.haskellstack.org/ | sh
    fi

- name: Upgrade Stack
  shell: stack upgrade

- name: Place stack.yaml for specified version of ghc install
  template:
    src: files/stack.yaml
    dest: ~/.stack/global-project/stack.yaml

- name: Reinstall ghc
  shell: stack setup

- name: Install useful packages
  shell: stack install '{{ item }}'
  with_items: '{{ STACK_PACKAGES }}'
