- name: Install Dependencies
  apt:
    name: '{{ APT_PACKAGES }}'
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Install Stack
  shell: |
    if ! which stack > /dev/null 2>&1; then
      curl -sSL https://get.haskellstack.org/ | sh
    fi
  args:
    executable: /bin/bash

- name: Upgrade Stack
  shell: stack upgrade
  args:
    executable: /bin/bash

- name: Create target directory for stack.yaml
  file: path=~/.stack/global-project state=directory mode=0755

- name: Place stack.yaml for specified version of ghc install
  template:
    src: files/stack.yaml
    dest: ~/.stack/global-project/stack.yaml

- name: Reinstall ghc
  shell: stack setup
  args:
    executable: /bin/bash

- name: Install useful packages
  shell: stack install '{{ item }}'
  args:
    executable: /bin/bash
  with_items: '{{ STACK_PACKAGES }}'
