- name: Install Stack
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - haskell-stack

- name: Place stack.yaml for specified version of ghc install
  template:
    src: files/stack.yaml
    dest: ~/.stack/global-project/stack.yaml

- name: Reinstall ghc
  shell: stack setup

- name: Install ghc-mod, hlint, hdevtools
  shell: stack install '{{ item }}'
  with_items:
    - ghc-mod
    - hlint
    - hdevtools
    - parsec
    - regex-posix
    - QuickCheck
    - HDBC
    - HDBC-sqlite3
