# fe [FUZZY PATTERN] - Open the selected file with the default editor
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
function fe() {
  file=$(fzf --query="$1" --select-1 --exit-0)
  if [ -f "$file" ] ; then
    nvim "$file"
  fi
}

# fzf kill
function fzf-kill() {
  ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -15
}
alias fk="fzf-kill"

# direnv
eval "$(direnv hook bash)"
