min_version = "2025.12.0"

[tools]
#----------------------
# node
#----------------------
node = "24"
pnpm = "10"
"npm:neovim" = "latest"
"npm:@antfu/ni" = "latest"
"npm:taze" = "latest"
# linter
"npm:knip" = "latest"
"npm:depcheck" = "latest"
"npm:ts-prune" = "latest"
# coding agent
"npm:@anthropic-ai/claude-code" = "latest"
"npm:happy-coder" = "latest"
"npm:difit" = "latest"

#----------------------
# python
#----------------------
python = "3"
ruff = "latest"
uv = "latest"

#----------------------
# ruby
#----------------------
ruby = "3"

#----------------------
# go
#----------------------
go = "1"
"go:github.com/air-verse/air" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/spf13/cobra-cli" = "latest"
"go:github.com/x-motemen/ghq" = "latest"
# protobuf
"go:github.com/golang/protobuf/protoc-gen-go" = "latest"
"go:github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc" = "latest"
"go:github.com/ktr0731/evans" = "latest"
# terraform
"go:github.com/plumber-cd/terraform-backend-git" = "latest"
"go:github.com/terraform-docs/terraform-docs" = "latest"

#----------------------
# terraform
#----------------------
terraform = "latest"

[env]
#----------------------
# node
#----------------------
# This will make CLIs installed with npm available without npx.
_.path = ["{{config_root}}/node_modules/.bin"]

[settings]
fetch_remote_versions_timeout = "60s"
