# Load bash flagment
if [ -d "${HOME}/.bash.d" ] ; then
    for f in "${HOME}"/.bash.d/*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Load local env file
if [ -f "$HOME/.env" ]; then
	. "$HOME/.env"
fi

# direnv
eval "$(direnv hook bash)"

export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8
export PATH=$PATH:$HOME/.local/bin:$HOME/bin

# mac alias
export PATH=$PATH:/Users/terakoya76/Library/Python/3.9/bin
export PATH=$PATH:/opt/homebrew/bin