- name: Install rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: Place rustup path
  template:
    src: files/rustup.sh
    dest: "$HOME/.bash.d/rustup.sh"
    mode: 0755

- name: Enable cargo
  shell: exec $SHELL -l
