---
- name: Install ebcli
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.pip:
    name: awsebcli
    state: present
    executable: pip3
  tags:
    - config-tool
    - config-aws
