---
- name: Get ansible_user home directory
  ansible.builtin.shell: 'set -o pipefail && getent passwd "{{ ansible_user }}" | cut -d: -f6'
  register: ansible_home_result
  tags:
    - config-tool
    - config-aws

- name: Set the fact for the other scripts to use
  ansible.builtin.set_fact: ansible_home='{{ansible_home_result.stdout}}'
  tags:
    - config-tool
    - config-aws

- name: Mkdir for aws config
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    path: "{{ ansible_home }}/.aws"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  tags:
    - config-tool
    - config-1password

- name: Place aws/config for awscli
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.template:
    src: files/awsconfig
    dest: "{{ ansible_home }}/.aws/config"
    mode: 0755
    backup: true
  tags:
    - config-tool
    - config-aws
