---
- name: Mkdir for aws config
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    path: "{{ ansible_home }}/.aws"
    state: directory
    owner: "{{ ansible_user }}"
    group: staff
    mode: 0755
  tags:
    - config-tool
    - config-aws

- name: Place aws/config for awscli
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.template:
    src: files/awsconfig
    dest: "{{ ansible_home }}/.aws/config"
    mode: 0755
    backup: true
  tags:
    - config-tool
    - config-aws

- name: Ensure a temporary directory for awscli download
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.tempfile:
    state: directory
  register: awscli_temp_dir
  tags:
    - config-tool
    - config-aws

- name: Download awscli install package
  become: true
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/AWSCLIV2.pkg
    dest: "{{ awscli_temp_dir.path }}/AWSCLIV2.pkg"
    mode: 0644
  tags:
    - config-tool
    - config-aws

- name: Install awscli
  become: true
  ansible.builtin.command: "installer -pkg {{ awscli_temp_dir.path }}/AWSCLIV2.pkg -target /"
  tags:
    - config-tool
    - config-aws

- name: Tap saml2aws
  become: true
  become_user: "{{ ansible_user }}"
  community.general.homebrew_tap:
    name: versent/homebrew-taps
    state: present
  tags:
    - config-tool
    - config-aws

- name: Install saml2aws
  become: true
  become_user: "{{ ansible_user }}"
  community.general.homebrew:
    name: saml2aws
    state: present
  tags:
    - config-tool
    - config-aws
