- name: Ensure goenv installed
  shell: bash -l -c 'which goenv'
  changed_when: false

- name: Check installed golang version
  shell: bash -l -c 'goenv versions'
  register: GOENV_INSTALLED
  changed_when: false
  ignore_errors: yes

- name: Install golang from goenv
  shell: bash -l -c 'goenv install {{ item }}'
  when: 'item not in GOENV_INSTALLED.stdout'
  with_items: '{{ GOLANG_VERSIONS }}'

- name: Install golang libraries
  shell: go get -u '{{ item.url }}'
  with_items: '{{ GOLANG_LIBERARIES }}'

- name: Install grpcurl
  shell: |
    go get -u github.com/fullstorydev/grpcurl
    go install github.com/fullstorydev/grpcurl/cmd/grpcurl
