---
- name: Install clang
  become: true
  ansible.builtin.apt:
    name:
      - clang-format
      - clang-tidy
      - clang-tools
      - clang
      - clangd
      - libclang-dev
      - libclang1
      - python3-clang
    state: present
  tags:
    - config-language
    - config-llvm

- name: Install libc++
  become: true
  ansible.builtin.apt:
    name:
      - libc++-dev
      - libc++1
      - libc++abi-dev
      - libc++abi1
    state: present
  tags:
    - config-language
    - config-llvm

- name: Install OpenMP
  become: true
  ansible.builtin.apt:
    name:
      - libomp-dev
      - libomp5
    state: present
  tags:
    - config-language
    - config-llvm

- name: Install lld
  become: true
  ansible.builtin.apt:
    name:
      - lld
    state: present
  tags:
    - config-language
    - config-llvm

- name: Install lldb
  become: true
  ansible.builtin.apt:
    name:
      - liblldb-dev
      - lldb
    state: present
  tags:
    - config-language
    - config-llvm

- name: Install llvm
  become: true
  ansible.builtin.apt:
    name:
      - libllvm-ocaml-dev
      - llvm-dev
      - llvm-runtime
      - llvm
    state: present
  tags:
    - config-language
    - config-llvm
