---
- name: Get ansible_user home directory
  ansible.builtin.shell: 'set -o pipefail && getent passwd "{{ ansible_user }}" | cut -d: -f6'
  register: ansible_home_result
  changed_when: false
  tags:
    - config-tool
    - config-kubernetes

- name: Set the fact for the other scripts to use
  ansible.builtin.set_fact: ansible_home={{ ansible_home_result.stdout }}
  changed_when: false
  tags:
    - config-tool
    - config-kubernetes

- name: For all
  ansible.builtin.import_tasks: common.yml

- name: For debian
  ansible.builtin.import_tasks: debian.yml
  when:
    - ansible_os_family == "Debian"

- name: For darwin
  ansible.builtin.import_tasks: darwin.yml
  when:
    - ansible_os_family == "Darwin"
