- name: Place kubeconfig.sh
  template:
    src: files/kubeconfig.sh
    dest: "$HOME/.bash.d/kubeconfig.sh"
    mode: 0755

- name: Enable kubectl
  shell: exec $SHELL -l

- name: Install helm
  homebrew:
    name: kubernetes-helm
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: helm init
  shell: helm init --history-max 200
  args:
    executable: /bin/bash

- name: Install Helm Plugin
  shell: |
    helm plugin install https://github.com/rimusz/helm-tiller
    helm plugin install https://github.com/databus23/helm-diff --version master
    helm plugin install https://github.com/futuresimple/helm-secrets
  args:
    executable: /bin/bash

- name: Install Helmfile
  shell: |
    SYSNAME="$(uname -s | tr '[A-Z]' '[a-z]')_amd64"
    curl -s https://api.github.com/repos/roboll/helmfile/releases/latest | jq -r --arg SYSNAME "$SYSNAME" '.assets[] | select(.name | contains($SYSNAME)) | .browser_download_url' | wget -i -
    mv "helmfile_$SYSNAME" /usr/local/bin
    chmod +x /usr/local/bin
  args:
    executable: /bin/bash

- name: Install stern
  shell: |
    SYSNAME="$(uname -s | tr '[A-Z]' '[a-z]')_amd64"
    curl -s https://api.github.com/repos/wercker/stern/releases/latest | jq -r --arg SYSNAME "$SYSNAME" '.assets[] | select(.name | contains($SYSNAME)) | .browser_download_url' | wget -i -
    mv "stern_$SYSNAME" /usr/local/bin
    chmod +x /usr/local/bin
  args:
    executable: /bin/bash

- name: Install kube-ps1
  homebrew:
    name: kube-ps1
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: Install awscli
  shell: pip3 install awscli --upgrade --user

- name: Install yq
  shell: pip3 install yq

- name: Install onelogin-aws-cli
  shell: pip3 install onelogin-aws-cli

- name: Install aws-iam-authenticator
  shell: go get -u github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator
  args:
    executable: /bin/bash

- name: Install sopsed
  shell: |
    curl -s https://api.github.com/repos/mumoshu/sopsed/releases/latest | jq -r ".assets[] | .browser_download_url" | wget -i -
    mv sopsed /usr/local/bin
    chmod +x /usr/local/bin
  args:
    executable: /bin/bash

- name: Install variant
  shell: |
    SYSNAME="$(uname -s | tr '[A-Z]' '[a-z]')_amd64"
    curl -s https://api.github.com/repos/mumoshu/variant/releases/latest | jq -r --arg SYSNAME "$SYSNAME" '.assets[] | select(.name | contains($SYSNAME)) | .browser_download_url' | wget -i -
    tar zxvf "variant_$VERSION_$SYSNAME.tar.gz"
    mv "variant" /usr/local/bin
    chmod +x /usr/local/bin
  args:
    executable: /bin/bash
