---
- name: Install OpenJDK
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk@8
    - openjdk@11
    - openjdk@17
  tags:
    - config-language
    - config-java

- name: Install gradle
  homebrew:
    name: gradle
    state: present
  tags:
    - config-language
    - config-java
