---
- name: Install OpenJDK
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jdk
    - openjdk-11-jdk
    - openjdk-17-jdk
  tags:
    - config-language
    - config-java
