---
- name: Install OpenJDK
  become: true
  ansible.builtin.apt:
    name:
      - openjdk-8-jdk
      - openjdk-11-jdk
      - openjdk-17-jdk
    state: present
  tags:
    - config-language
    - config-java
