- name: Install OpenJDK
  homebrew_cask:
    name: '{{ item }}'
    state: present
  with_items:
    - java
    - java11
    - adoptopenjdk8
  when: "ansible_os_family == 'Darwin'"

- name: Install OpenJDK
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - openjdk-8-jdk
    - openjdk-11-jdk
  when: "ansible_os_family == 'Debian'"

- name: Place set_java_version.sh
  template:
    src: files/set_java_version.sh
    dest: "$HOME/.bash.d/set_java_version.sh"
    mode: 0755

- name: Install gradle
  homebrew:
    name: gradle
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: Create target directory for gradle properties
  file: path="$HOME/.gradle" state=directory mode=0755

- name: Place gradle.properties
  template:
    src: files/gradle.properties
    dest: "$HOME/.gradle/gradle.properties"
    mode: 0755
