- name: Place default .bash_profile
  template:
    src: files/bash_profile
    dest: "$HOME/.bash_profile"
    mode: 0755

- name: Place default .bashrc
  template:
    src: files/bashrc
    dest: "$HOME/.bashrc"
    mode: 0755

- name: Create target directory for bash fragments
  file: path="$HOME/.bash.d" state=directory mode=0755

- name: Place docker.sh
  template:
    src: files/bash.d/docker.sh
    dest: "$HOME/.bash.d/docker.sh"
    mode: 0755

- name: Place git.sh
  template:
    src: files/bash.d/git.sh
    dest: "$HOME/.bash.d/git.sh"
    mode: 0755

- name: Place history.sh
  template:
    src: files/bash.d/history.sh
    dest: "$HOME/.bash.d/history.sh"
    mode: 0755

- name: Place kubernetes.sh
  template:
    src: files/bash.d/kubernetes.sh
    dest: "$HOME/.bash.d/kubernetes.sh"
    mode: 0755

- name: Place tools.sh
  template:
    src: files/bash.d/tools.sh
    dest: "$HOME/.bash.d/tools.sh"
    mode: 0755

- name: Place .vimrc for vim
  template:
    src: files/vimrc
    dest: "$HOME/.vimrc"
    mode: 0755

- name: Create target directory for nvim
  file: path="$HOME/.config/nvim" state=directory mode=0755

- name: Place .vimrc for nvim
  template:
    src: files/vimrc
    dest: "$HOME/.config/nvim/init.vim"
    mode: 0755

- name: Create target directory for translate-shell
  file: path="$HOME/.translate-shell" state=directory mode=0755

- name: Place .init.trans
  template:
    src: files/init.trans
    dest: "$HOME/.translate-shell/init.trans"
    mode: 0755

- name: Place .tmux.conf
  template:
    src: files/tmux.conf
    dest: "$HOME/.tmux.conf"
    mode: 0755

- name: Create target directory for alacritty
  file: path="$HOME/.config/alacritty" state=directory mode=0755

- name: Place alacritty.yml
  template:
    src: files/alacritty.yml
    dest: "$HOME/.config/alacritty/alacritty.yml"
    mode: 0755

- name: Place my.cnf
  template:
    src: files/my.cnf
    dest: "$HOME/.my.cnf"
    mode: 0755

- name: Place .gitignore_global
  template:
    src: files/gitignore_global
    dest: "$HOME/.gitignore_global"
    mode: 0755

- name: Enable dotfiles
  shell: git config --global core.excludesfile ~/.gitignore_global
