- name: Brew Tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items:
    - osx-cross/avr
    - PX4/homebrew-px4
  when: "ansible_os_family == 'Darwin'"

- name: Brew Update
  shell: brew update
  when: "ansible_os_family == 'Darwin'"

- name: Brew Install
  homebrew:
    name: '{{ item }}'
    state: present
  with_items:
    - avr-gcc@7
    - dfu-programmer
    - gcc-arm-none-eabi
    - avrdude
  when: "ansible_os_family == 'Darwin'"
