- name: Install kubectl
  shell: brew install kubernetes-cli
  when: "ansible_os_family == 'Darwin'"
  args:
    executable: /bin/bash

- name: Install kubectl
  become: yes
  shell: |
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    mv ./kubectl /usr/local/bin/kubectl
    chmod +x /usr/local/bin/kubectl
  when: ("ansible_os_family == 'Debian'")
  args:
    executable: /bin/bash

- name: Install helm
  shell: https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
  args:
    executable: /bin/bash

- name: Install stern
  shell: brew install stern
  when: "ansible_os_family == 'Darwin'"
  args:
    executable: /bin/bash

- name: Install kube-ps1
  shell: brew install kube-ps1
  when: "ansible_os_family == 'Darwin'"
  args:
    executable: /bin/bash

- name: Install awscli
  shell: pip3 install awscli --upgrade --user
  args:
    executable: /bin/bash

- name: Install onelogin-aws-cli
  shell: pip3 install onelogin-aws-cli
  args:
    executable: /bin/bash

- name: Install eksctl
  become: yes
  shell: |
    curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
    mv /tmp/eksctl /usr/local/bin
    chmod +x /usr/local/bin
  args:
    executable: /bin/bash

- name: Install aws-iam-authenticator
  shell: go get -u github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator
  args:
    executable: /bin/bash

- name: Install terraform
  shell: brew install terraform
  when: "ansible_os_family == 'Darwin'"
  args:
    executable: /bin/bash

- name: Install terraform
  become: yes
  shell: |
    wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    unzip terraform_0.11.11_linux_amd64.zip
    mv ./terraform /usr/bin/
  when: ("ansible_os_family == 'Debian'")
  args:
    executable: /bin/bash
