- name: Ensure nodenv installed
  shell: bash -l -c 'which nodenv'
  changed_when: false

- name: Check installed nodejs version
  shell: bash -l -c 'nodenv versions'
  register: NODENV_INSTALLED
  changed_when: false
  ignore_errors: yes

- name: Install nodejs from nodenv
  shell: bash -l -c 'nodenv install {{ item }}'
  when: 'item not in NODENV_INSTALLED.stdout'
  with_items: '{{ NODEJS_VERSIONS }}'

- name: Set Global version
  shell: bash -l -c 'nodenv global {{ GLOBAL_VERSION }}'

- name: Write yarn path
  lineinfile:
    dest: ~/.bash.d/yarn.sh
    line: export PATH="$HOME/.yarn/bin:$PATH"
    create: yes
    mode: 755
