- name: Ensure nodenv installed
  shell: which nodenv
  changed_when: false

- name: Check installed nodejs version
  shell: nodenv versions
  register: NODENV_INSTALLED
  changed_when: false
  ignore_errors: yes

- name: Install nodejs from nodenv
  shell: nodenv install '{{ item }}'
  when: 'item not in NODENV_INSTALLED.stdout'
  with_items: '{{ NODEJS_VERSIONS }}'

- name: Install JS lsp
  npm:
    name: flow-language-server
    global: true

- name: Install TS
  npm:
    name: typescript
    global: true

- name: Install TS lsp
  npm:
    name: typescript-language-server
    global: true

- name: Install CSS lsp
  npm:
    name: vscode-css-languageserver-bin
    global: true

- name: Set Global version
  shell: nodenv global '{{ GLOBAL_VERSION }}'

- name: Place yarn.sh
  template:
    src: files/yarn.sh
    dest: "$HOME/.bash.d/yarn.sh"
    mode: 0755

- name: Enable yarn
  shell: $SHELL -l
