- name: Install Docker
  homebrew_cask:
    name: docker-edge
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: Install dependencies
  become: yes
  apt:
    name: '{{ APT_PACKAGES }}'
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Add Apt-Repository
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  when: "ansible_os_family == 'Debian'"

- name: Install Docker
  become: yes
  apt:
    name: docker-ce
    state: present
  when: "ansible_os_family == 'Debian'"
