STACK_PACKAGES:
  - ghc-mod
  - hlint
  - hdevtools
  - parsec
  - regex-posix
  - QuickCheck
  - HDBC
  - HDBC-sqlite3

APT_PACKAGES:
  - g++
  - gcc
  - libc6-dev
  - libffi-dev
  - libgmp-dev
  - make
  - xz-utils
  - zlib1g-dev
  - git
  - gnupg
