- name: Install OpenJDK
  homebrew_cask:
    name: java
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: Install OpenJDK
  homebrew_tap:
    name: caskroom/versions
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: Install OpenJDK
  homebrew:
    name: java8
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: Install OpenJDK
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - openjdk-8-jdk
    - openjdk-11-jdk
  when: ("ansible_os_family == 'Debian'") or ("ansible_os_family == 'Linuxmint'")

- name: add jvm to under jenv management
  shell: |
    jenv add $(/usr/libexec/java_home)
    jenv add /Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/
  args:
    executable: /bin/bash
  when: "ansible_os_family == 'Darwin'"

- name: add jvm to under jenv management
  shell: |
    jenv add /usr/lib/jvm/java-8-openjdamd64
    jenv add /usr/lib/jvm/java-11-openjdk-amd64
  args:
    executable: /bin/bash
  when: ("ansible_os_family == 'Debian'") or ("ansible_os_family == 'Linuxmint'")

- name: Install gradle
  homebrew:
    name: gradle
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: Create target directory for gradle properties
  file: path="$HOME/.gradle" state=directory mode=0755

- name: Place gradle.properties
  template:
    src: files/gradle.properties
    dest: "$HOME/.gradle/gradle.properties"
    mode: 0755
