---
- name: Add Apt-Repository 1Password App
  become: true
  shell: |
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
    echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' > /etc/apt/sources.list.d/1password.list
  tags:
    - config-1password

- name: Add Debsig-Verify 1Password App
  become: true
  shell: |
    mkdir -p /etc/debsig/policies/AC2D62742012EA22/
    curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol > /etc/debsig/policies/AC2D62742012EA22/1password.pol
    sudo mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
  tags:
    - config-1password

- name: Install 1Password App
  become: true
  apt:
    name:
      - 1password
      - 1password-cli
    state: present
    update_cache: yes
  when: not ansible_check_mode
  tags:
    - config-1password
