- name: Install Rictyfont
  shell: |
    brew tap sanemat/font
    brew install ricty
    cp -f /usr/local/opt/ricty/share/fonts/Ricty*.ttf ~/Library/Fonts/
    fc-cache -vf
  when: "ansible_os_family == 'Darwin'"

- name: Install Rictyfont Dependencies
  become: yes
  apt:
    name: '{{ APT_PACKAGES }}'
    state: present
  when: "ansible_os_family == 'Debian'"

- name: Create target directory for Rictyfont
  file: path="$HOME/.fonts" state=directory mode=0755
  when: "ansible_os_family == 'Debian'"

- name: Create tmp directory
  file: path=/tmp/ricty-XXXXX state=directory mode=0755
  when: "ansible_os_family == 'Debian'"

- name: Install Migu 1M
  shell: |
    wget http://iij.dl.sourceforge.jp/mix-mplus-ipa/59022/migu-1m-20130617.zip
    unzip migu-1m-*.zip
    cp migu-1m-*/*.ttf "$HOME/.fonts/"
  args:
    executable: /bin/bash
    chdir: /tmp/ricty-XXXXX
  when: "ansible_os_family == 'Debian'"

- name: Install Ricty
  shell: |
    wget http://www.rs.tus.ac.jp/yyusa/ricty/ricty_generator.sh
    wget http://www.rs.tus.ac.jp/yyusa/ricty/os2version_reviser.sh
    chmod 755 ricty_generator.sh os2version_reviser.sh
    ./ricty_generator.sh auto
    ./os2version_reviser.sh Ricty*.ttf
    cp -f Ricty*.ttf ~/.fonts/
    fc-cache -vf
  args:
    executable: /bin/bash
    chdir: /tmp/ricty-XXXXX
  when: "ansible_os_family == 'Debian'"

- name: Cleanup tmp files
  shell: rm -fr /tmp/ricty-XXXXX/
  when: "ansible_os_family == 'Debian'"
